---
all:
  children:
    writefreely:
      hosts:
        production:
          ansible_host: 203.0.113.10
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/writefreely-vps
